name: Code Coverage

on:
  pull_request:
    types: [ closed ]
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov codecov
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --cov=./peepingtom
      - name: Upload report to codecov
        if: github.event.pull_request.merged == true
        run: |
          codecov
          bash <(curl -s https://codecov.io/bash)
